---
- hosts: localhost
  become: true
  vars_files:
    - keys.yml
  tasks:
    - name: create ebs 
      ec2_vol:
        aws_access_key: "{{ AWS_KEY_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        zone: "us-east-1a"
        volume_size: 1  
        name: new_volume
        device_name: /dev/xvdf
      register: volume
    
    - name: stop instance to attach volume
      ec2:
        aws_access_key: "{{ AWS_KEY_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: stopped
        instance_tags:
          Name: Demo-ec2-centos7

    - name: debug output
      debug:
        var: volume

    - name: attach the volume to an instance
      ec2_vol:
        aws_access_key: "{{ AWS_KEY_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance: i-0b191d99aa26b6954
        id: vol-0cb71d045f891788a
        delete_on_termination: yes
      register: output

    - name: display output
      debug:
        var: output
    - name: start instance to attach volume
      ec2:
        aws_access_key: "{{ AWS_KEY_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        state: running
        instance_tags:
          Name: Demo-ec2-centos7
