---
- hosts: localhost
  become: true
  vars_files:
    - keys.yml
  tasks:
    - name: gather snapshot facts
      ec2_snapshot_facts:
        aws_access_key: "{{ AWS_KEY_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"

    - name: create volume snapshot
      ec2_snapshot:
        aws_access_key: "{{ AWS_KEY_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        instance_id: i-0b191d99aa26b6954
        device_name: /dev/sda1
        state: present
        description: "On demand volume backup."      
        


      
