---
- hosts: localhost
  become: true
  vars_files:
    - keys.yml
  tasks:
    - name: creating security group for a vpc
      ec2_group:
        aws_access_key: "{{ AWS_KEY_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        name: Test_SG
        description: TEST_SG
        vpc_id: vpc-0772de2a343b2a199
        rules:
          - proto: tcp
            ports:
              - 80
              - 443
              - 22
            cidr_ip: 0.0.0.0/0

