---
- hosts: localhost
  become: true
  vars_files:
    - keys.yml
  tasks:
    - name: gather vpc facts
      ec2_vpc_net_info:
        aws_access_key: "{{ AWS_KEY_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
      register: vpc_facts

    - debug:
        var: vpc_facts.vpcs[1].vpc_id
    
    - name: get subnet facts
      ec2_vpc_subnet_info:
        aws_access_key: "{{ AWS_KEY_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        filters:
          vpc-id: "{{ vpc_facts.vpcs[2].vpc_id }}"
      register: vpc_subnets
    - debug:
        var: vpc_subnets.subnets[0].subnet_id
    - name: get ec2 facts
      ec2_instance_info:
        aws_access_key: "{{ AWS_KEY_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}" 
        filters:
          tag:Name: Demo-ec2-centos7
      register: ec2_facts
    - debug: 
        msg: "SG ID IS: {{ ec2_facts.instances[0].security_groups[0].group_id }}"


        
