---
- hosts: localhost
  become: true
  vars_files: 
    - keys.yml
  tasks:
    - name: collect ami facts
      ec2_ami_facts:
        aws_access_key: "{{ AWS_KEY_ACCESS_ID }}"
        aws_secret_key: "{{ AWS_SECRET_KEY }}"
        ec2_region: "{{ AWS_REGION }}"
        #owner: "{{ AWS_OWNER }}"
        filters:
          description: "*redhat*"
      register: ami_facts
    - name: output informations
      debug:
        msg: "{{ item.description }}"
      loop_control:
        label: "{{ item.image_id }}"
      loop: "{{ ami_facts.images }}"
          
